# This file was generated by GoReleaser. DO NOT EDIT.
cask "lasd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6a96d0a3682ae46bb8ec07604bcb67d8bbb95009760b83fc313da1ef64409f13"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58cd8a4f136d9fc3f6bf155b456b202beb2e9f88cb07e18d11d96ee1a1a5c0f3"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36586fd39a031e91f65b7b4acda0b2d81bbad5af0645e5ea3d3895f6cb4dd8ad"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce14a681efe3429f127d8085d9e98f4fc72767d96654bd1243252691be0ffd40"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lasd"
  desc "Run kubernetes-sigs/agent-sandbox locally on Docker"
  homepage "https://github.com/dvaldivia/local-agent-sandbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lasd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lasd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lasd needs a running Docker daemon (Docker Desktop, Colima, or OrbStack).

    Start the local control plane:
      lasd serve
    Point your tooling and the agent-sandbox SDKs at it:
      export KUBECONFIG=~/.local/share/local-agent-sandbox/kubeconfig
  EOS
end
