# This file was generated by GoReleaser. DO NOT EDIT.
cask "lasd" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "d16d5358902e8ac115ef62b27e5c6e30b04c1cd04ef7121b5e274bb50f1a053a"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98ca628cbce345ad63c835ad623591347215a53503be2f3dfe70e36ec3902806"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6395f83d923d30b0c5cec871af74494867f28e7832ff0ef820a2fce9e0964f60"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7ece6d3b26b0bdf643146cf0240f420b8f0b3193d611b46e3f71c96a0617720"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lasd"
  desc "Run kubernetes-sigs/agent-sandbox locally on Docker"
  homepage "https://github.com/dvaldivia/local-agent-sandbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lasd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lasd"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lasd needs a running Docker daemon (Docker Desktop, Colima, or OrbStack).

    Start the local control plane:
      lasd serve
    Point your tooling and the agent-sandbox SDKs at it:
      export KUBECONFIG=~/.local/share/local-agent-sandbox/kubeconfig
  EOS
end
