# This file was generated by GoReleaser. DO NOT EDIT.
cask "lasd" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "eeda8745764d22c4d770ee95ad21932a9195a6c043437bcade272d2021bdc778"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a39cae139f65bfc9debd9a90ed3f4d6f861f3cd540e6baff8bf0fe5fc6574f9"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da34e9317346526ef2ba63c6452bac8a2b4c489789e41beabe2762d8bb4eb24c"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "000aa18b3543047ade046895a76b45d8cfa7612ecc9060d3cf12014cb8d86a8e"
      url "https://github.com/dvaldivia/local-agent-sandbox/releases/download/v#{version}/lasd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lasd"
  desc "Run kubernetes-sigs/agent-sandbox locally on Docker"
  homepage "https://github.com/dvaldivia/local-agent-sandbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lasd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lasd"], must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    lasd needs a running Docker daemon (Docker Desktop, Colima, or OrbStack).

    Start the local control plane:
      lasd serve
    Point your tooling and the agent-sandbox SDKs at it:
      export KUBECONFIG=~/.local/share/local-agent-sandbox/kubeconfig
  EOS
end
